version: '3.3'

services:
  frontend:
    image: hmzza/frontend-service:v1
    ports:
      - "3000:3000"
    networks:
      - isolated_net

  appointments:
    image: hmzza/appointments-service:d7fc58f8c83404a6aee69e81ead6f302b4d3c586
    ports:
      - "7070:7070"
    networks:
      - isolated_net

  doctors:
    image: hmzza/doctor-service:c5e78aa161f3ee0d08ae8b49727f51551e0b25c0
    ports:
      - "9090:9090"
    networks:
      - isolated_net

networks:
  isolated_net:
