version: '3.3'

services:
  frontend:
    image: hmzza/frontend-service:v1
    ports:
      - "3000:3000"
    networks:
      - isolated_net

  appointments:
    image: hmzza/appointments-service:09ccbebb71a77a743fa5db0ed63b505ca447168b
    ports:
      - "7070:7070"
    networks:
      - isolated_net

  doctors:
    image: hmzza/doctor-service:4d1ebd6d8854126e01a554ff1b9b8e3c7aa1c580
    ports:
      - "9090:9090"
    networks:
      - isolated_net

networks:
  isolated_net:
