version: '3.3'

services:
  frontend:
    image: hmzza/frontend-service:a31b8b3bf9fe005723328295957be10acef45677
    ports:
      - "3000:3000"
    networks:
      - isolated_net

  appointments:
    image: hmzza/appointments-service:5468900944109789460bd5eabe4538b74e6579c7
    ports:
      - "7070:7070"
    networks:
      - isolated_net

  doctors:
    image: hmzza/doctor-service:0d9f39afac65f7723c0db4c682624513f4282857
    ports:
      - "9090:9090"
    networks:
      - isolated_net
  
  mysql:
    image: mysql:latest
    environment:
        MYSQL_ROOT_PASSWORD: hmzza
        MYSQL_DATABASE: mydb_test
        MYSQL_USER: hmzza
        MYSQL_PASSWORD: hamzadb123

    ports:
      - "3306:3306"


networks:
  isolated_net:
