version: '3.3'

services:
  frontend:
    image: hmzza/frontend-service:v1
    ports:
      - "3000:3000"
    networks:
      - isolated_net

  appointments:
    image: hmzza/appointments-service:7f94000ed2f501ec1adc641f09dbb1828ff92d77
    ports:
      - "7070:7070"
    networks:
      - isolated_net

  doctors:
    image: hmzza/doctor-service:0d9f39afac65f7723c0db4c682624513f4282857
    ports:
      - "9090:9090"
    networks:
      - isolated_net

networks:
  isolated_net:
