apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: hmzza/frontend-service:a31b8b3bf9fe005723328295957be10acef45677
        ports:
        - containerPort: 3000
        env:
          - name: DOCTORS_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                  name: frontend-config
                  key: DOCTORS_SERVICE_URL
          - name: APPOINTMENTS_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-config
                key: APPOINTMENTS_SERVICE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /hello
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /hello
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  DOCTORS_SERVICE_URL: "doctors-service.default.svc.cluster.local:9090"
  APPOINTMENTS_SERVICE_URL: "appointment-service.default.svc.cluster.local:7070"
