name: Doctors Service CI/CD

on:
  push:
    branches: [main]
    # paths:
    #   - "doctors/**"
  pull_request:
    branches: [main]
    paths:
      - "doctors/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env: 
          DOCKER_USER:  ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t hmzza/doctor-service:${{ github.sha }} doctors/
          docker push hmzza/doctor-service:${{ github.sha }}

      - name: Update docker-compose file
        run: |
          sed -i 's|hmzza/doctor-service:.*|hmzza/doctor-service:${{ github.sha }}|' docker-compose.yml
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docker-compose.yml
          git commit -m "Update docker-compose for doctor service with new image tag ${{ github.sha }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
